services:
  auth:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  tasks:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"