apiVersion: v1
kind: Secret
metadata:
  name: tasks-secrets
  namespace: techip
type: Opaque
stringData:
  DB_USER: "appuser"
  DB_PASSWORD: "AppP@ssw0rd!2026"
  AUTH_GRPC_ADDR: "193.233.175.221:50051"  # сервер