events {
    worker_connections 1024;
}

http {
    upstream tasks_service {
        server tasks:8082;
    }

    upstream auth_service {
        server auth:8081;
    }

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-ID $http_x_request_id;

    server {
        listen 8443 ssl;
        server_name 193.233.175.221 localhost;

        # SSL сертификаты
        ssl_certificate /opt/techip/certs/cert.pem;
        ssl_certificate_key /opt/techip/certs/key.pem;
        
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Логирование
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Tasks endpoints
        location /v1/tasks/search {
            proxy_pass http://tasks_service/v1/tasks/search;
            proxy_set_header Authorization $http_authorization;
            proxy_redirect off;
        }

        location /v1/tasks {
            proxy_pass http://tasks_service/v1/tasks;
            proxy_set_header Authorization $http_authorization;
            proxy_redirect off;
        }

        location /v1/tasks/ {
            proxy_pass http://tasks_service/v1/tasks/;
            proxy_set_header Authorization $http_authorization;
            proxy_redirect off;
        }

        # Auth endpoints
        location /v1/auth {
            proxy_pass http://auth_service/v1/auth;
            proxy_set_header Authorization $http_authorization;
            proxy_redirect off;
        }

        location /v1/auth/ {
            proxy_pass http://auth_service/v1/auth/;
            proxy_set_header Authorization $http_authorization;
            proxy_redirect off;
        }

        # Health check
        location /health {
            proxy_pass http://tasks_service/health;
            proxy_redirect off;
        }

        location / {
            return 200 "HTTPS Gateway is working!\n";
            add_header Content-Type text/plain;
        }
    }
}